# Generated by Django 3.2.12 on 2022-04-10 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0003_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRunRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='请求的url')),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方式')),
                ('data', models.TextField(null=True, verbose_name='提交的数据')),
                ('headers', models.TextField(null=True, verbose_name='提交的header')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='运行的时间')),
                ('return_code', models.CharField(max_length=10, verbose_name='返回的code')),
                ('return_content', models.TextField(null=True, verbose_name='返回的内容')),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_test.api', verbose_name='关联的api')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
