# Generated by Django 3.2.12 on 2022-04-21 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0008_caseapirunrecord_caserunrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('expr', models.CharField(max_length=255, verbose_name='任务执行表达式')),
                ('status', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='任务状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.case', verbose_name='定时执行的用例')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务创建者')),
            ],
        ),
    ]
